### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by hydragenesis** [ybd-project-ver1/ytdl-core#13]
I'm getting this error on NodeJS v16.20.0 with v6

ReferenceError: Headers is not defined
    at Function.fetch (C:\Users\Administrator\Desktop\GoatbotV2\node_modules\@ybd-project\ytdl-core\bundle\node.cjs:858:118125)
    at Function.request (C:\Users\Administrator\Desktop\GoatbotV2\node_modules\@ybd-project\ytdl-core\bundle\node.cjs:858:118789)
    at getHtml5Player (C:\Users\Administrator\Desktop\GoatbotV2\node_modules\@ybd-project\ytdl-core\bundle\node.cjs:872:1260)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ReferenceError: Headers is not defined
    at Function.fetch (C:\Users\Administrator\Desktop\GoatbotV2\node_modules\@ybd-project\ytdl-core\bundle\node.cjs:858:118125)
    at Function.request (C:\Users\Administrator\Desktop\GoatbotV2\node_modules\@ybd-project\ytdl-core\bundle\node.cjs:858:118789)
    at getHtml5Player (C:\Users\Administrator\Desktop\GoatbotV2\node_modules\@ybd-project\ytdl-core\bundle\node.cjs:872:1260)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _getBasicInfo (C:\Users\Administrator\Desktop\GoatbotV2\node_modules\@ybd-project\ytdl-core\bundle\node.cjs:883:10320)
    at async _getFullInfo (C:\Users\Administrator\Desktop\GoatbotV2\node_modules\@ybd-project\ytdl-core\bundle\node.cjs:883:25536)
    at async getFullInfo (C:\Users\Administrator\Desktop\GoatbotV2\node_modules\@ybd-project\ytdl-core\bundle\node.cjs:883:26490)

**Comment by ybd-project-ver1** [comment]
Thank you for your report. We are aware of this issue and will fix it in v6.0.2 using the headers-polyfill package.

**Comment by hydragenesis** [comment]
Okay bro

**Comment by hydragenesis** [comment]
Btw can you give a temporary fix for this?

**Comment by ybd-project-ver1** [comment]
To temporarily solve this problem, define a Header in global (`global.Headers = PolyfillHeader;`)

**Comment by hydragenesis** [comment]
I tried but it still keeps saying header isn't defined

const fs = require('fs');
const path = require('path');
const fetch = require('node-fetch');
global.fetch = fetch;
global.Headers = fetch.Headers;
const { YtdlCore } = require('@ybd-project/ytdl-core');
const yts = require('yt-search');

**Comment by ybd-project-ver1** [comment]
Soon, v6.0.2 will be released which fixes this problem.

**Comment by ybd-project-ver1** [comment]
I believe this problem has been fixed in v6.0.2. Please try the latest version.
